name: Reauth with Bot Protection - Authenticate - Missing Bot Protection Input
authgear.yaml:
  override: |
    bot_protection:
      enabled: true
      provider:
        type: cloudflare
        site_key: dummy
# Not using user imports because we need userID in generateIDToken
before:
  - type: custom_sql
    custom_sql:
      path: reauth_user_2.sql
steps:
  - action: "create"
    input: |
      {
        "type": "reauth",
        "name": "default"
      }
    output:
    # Note bot protection is not supported in reauth > identify
      result: |
        {
          "action": {
            "type": "identify"
          }
        }
  - action: input
    input: |
      {
        "identification": "id_token",
        "id_token": "{{ generateIDToken "edaad8f0-74aa-4d6f-8d7f-f4edcb0c43c8" }}"
      }
    output:
      result: |
        {
          "state_token": "[[string]]",
          "type": "reauth",
          "name": "default",
          "action": {
            "type": "authenticate",
            "data": {
              "options": [
                "[[arrayof]]",
                {
                  "authentication": "[[string]]",
                  "bot_protection": {
                    "enabled": true,
                    "provider": {
                      "type": "cloudflare"
                    }
                  }
                }
              ],
              "type": "authentication_data"
            }
          }
        }
  - action: input
    input: |
      {
        "authentication": "primary_password",
        "password": "password",
        "bot_protection": {
          "type": "cloudflare",
          "response": "fail"
        }
      }
    output:
      error: |
        {
          "name": "Forbidden",
          "reason": "BotProtectionVerificationFailed",
          "message": "bot protection verification failed",
          "code": 403
        }
      